# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: CDC
run-name: Spyglass CDC from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 5 * * *'    # 5:30 AM (UTC), any day of the month, any month, any day of the week
  workflow_dispatch:

jobs:
  Lint-Spyglass-RTL-Handoff:
    runs-on: self-hosted        # runs on a server with Synopsys Spyglass installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Spyglass-Lint
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}
          action.lint
      - name: Report (moresimple)
        run: cat reports/moresimple.rpt
#      - name: Upload Lint report
#        uses: actions/upload-artifact@v3
#        with:
#          name: moresimple.rpt
#          path: reports/moresimple.rpt
