# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: Regression tests
run-name: Regression test for a pull request from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
jobs:
  Linux-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
#  compile:
#    runs-on: self-hosted        # runs on a server with Spyglass installed
#    steps:
  Spyglass-Lint-RTL-Handoff:
    runs-on: self-hosted        # runs on a server with Spyglass installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Spyglass
        run: |
          export DESIGN_TOP=AIDC_LITE_COMP_TOP_WRAPPER; \
          export AIDC_LITE_HOME=${{github.workspace}}; \
          export DESIGN_FILELIST=${{github.workspace}}/design/sverilog/filelist.f; \
          sg_shell < ${{github.workspace}}/actions/spyglass_lint/rtl_signoff.tcl
