# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: Regression tests
run-name: Regression test for a pull request from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
jobs:
  VCS-Compile-Only:
    runs-on: self-hosted        # runs on a server with Synopsys VCS installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: compile
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}; \
          action.compile_only
  VCS-Sim:
    runs-on: self-hosted        # runs on a server with Synopsys VCS installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: compile
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}; \
          action.sim; \
#../simv;
  Spyglass-Lint-RTL-Handoff:
    runs-on: self-hosted        # runs on a server with Synopsys Spyglass installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Spyglass
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}; \
          action.lint; \
      - name: moresimple.rpt
        run: cat reports/moresimple.rpt;
      - name: Upload summary report
        uses: actions/upload-artifact@v3
          with:
            name: moresimple.rpt
            path: reports/moresimple.rpt
