# This file describes a workflow that runs regression tests
# on a pull request to the main branch
name: Synthesis (Samsung 8nm)
run-name: IP-level synthesis (Samsung 28nm) from ${{ github.actor }}
on:
  schedule:
    - cron: '30 5 * * *'    # 5:30 AM (UTC) every day
jobs:
  Design-Compiler-UMC28nm:
    runs-on: self-hosted        # runs on a server with Synopsys Design Compiler installed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Synthesis
        run: |
          source ${{github.workspace}}/env.source ${{github.workspace}}
#           action.syn
